// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: robotmaid.proto

package housework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotmaid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_robotmaid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_robotmaid_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotmaid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_robotmaid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_robotmaid_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChoreNumber int32 `protobuf:"varint,1,opt,name=chore_number,json=choreNumber,proto3" json:"chore_number,omitempty"`
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotmaid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotmaid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_robotmaid_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteRequest) GetChoreNumber() int32 {
	if x != nil {
		return x.ChoreNumber
	}
	return 0
}

var File_robotmaid_proto protoreflect.FileDescriptor

var file_robotmaid_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x6d, 0x61, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x0f, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x0f,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x32, 0xa4, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4d, 0x61, 0x69, 0x64,
	0x12, 0x2d, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x11, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x1a, 0x13, 0x2e, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_robotmaid_proto_rawDescOnce sync.Once
	file_robotmaid_proto_rawDescData = file_robotmaid_proto_rawDesc
)

func file_robotmaid_proto_rawDescGZIP() []byte {
	file_robotmaid_proto_rawDescOnce.Do(func() {
		file_robotmaid_proto_rawDescData = protoimpl.X.CompressGZIP(file_robotmaid_proto_rawDescData)
	})
	return file_robotmaid_proto_rawDescData
}

var file_robotmaid_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_robotmaid_proto_goTypes = []interface{}{
	(*Empty)(nil),           // 0: housework.Empty
	(*Response)(nil),        // 1: housework.Response
	(*CompleteRequest)(nil), // 2: housework.CompleteRequest
	(*Chores)(nil),          // 3: housework.Chores
}
var file_robotmaid_proto_depIdxs = []int32{
	3, // 0: housework.RobotMaid.Add:input_type -> housework.Chores
	2, // 1: housework.RobotMaid.Complete:input_type -> housework.CompleteRequest
	0, // 2: housework.RobotMaid.List:input_type -> housework.Empty
	1, // 3: housework.RobotMaid.Add:output_type -> housework.Response
	1, // 4: housework.RobotMaid.Complete:output_type -> housework.Response
	3, // 5: housework.RobotMaid.List:output_type -> housework.Chores
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_robotmaid_proto_init() }
func file_robotmaid_proto_init() {
	if File_robotmaid_proto != nil {
		return
	}
	file_housework_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_robotmaid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotmaid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotmaid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_robotmaid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robotmaid_proto_goTypes,
		DependencyIndexes: file_robotmaid_proto_depIdxs,
		MessageInfos:      file_robotmaid_proto_msgTypes,
	}.Build()
	File_robotmaid_proto = out.File
	file_robotmaid_proto_rawDesc = nil
	file_robotmaid_proto_goTypes = nil
	file_robotmaid_proto_depIdxs = nil
}
