// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: users.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Users_GetUser_FullMethodName    = "/Users/GetUser"
	Users_CreateUser_FullMethodName = "/Users/CreateUser"
	Users_GetUsers_FullMethodName   = "/Users/GetUsers"
	Users_GetHelp_FullMethodName    = "/Users/GetHelp"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	// unary pattern
	GetUser(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*User, error)
	// server-side stream
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (Users_CreateUserClient, error)
	// client-side stream
	GetUsers(ctx context.Context, opts ...grpc.CallOption) (Users_GetUsersClient, error)
	// bi-directional stream
	GetHelp(ctx context.Context, opts ...grpc.CallOption) (Users_GetHelpClient, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetUser(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, Users_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (Users_CreateUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &Users_ServiceDesc.Streams[0], Users_CreateUser_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &usersCreateUserClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Users_CreateUserClient interface {
	Recv() (*UserCreateLog, error)
	grpc.ClientStream
}

type usersCreateUserClient struct {
	grpc.ClientStream
}

func (x *usersCreateUserClient) Recv() (*UserCreateLog, error) {
	m := new(UserCreateLog)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usersClient) GetUsers(ctx context.Context, opts ...grpc.CallOption) (Users_GetUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &Users_ServiceDesc.Streams[1], Users_GetUsers_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &usersGetUsersClient{stream}
	return x, nil
}

type Users_GetUsersClient interface {
	Send(*User) error
	CloseAndRecv() (*UsersList, error)
	grpc.ClientStream
}

type usersGetUsersClient struct {
	grpc.ClientStream
}

func (x *usersGetUsersClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *usersGetUsersClient) CloseAndRecv() (*UsersList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UsersList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usersClient) GetHelp(ctx context.Context, opts ...grpc.CallOption) (Users_GetHelpClient, error) {
	stream, err := c.cc.NewStream(ctx, &Users_ServiceDesc.Streams[2], Users_GetHelp_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &usersGetHelpClient{stream}
	return x, nil
}

type Users_GetHelpClient interface {
	Send(*UserHelpRequest) error
	Recv() (*UserHelpResponse, error)
	grpc.ClientStream
}

type usersGetHelpClient struct {
	grpc.ClientStream
}

func (x *usersGetHelpClient) Send(m *UserHelpRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *usersGetHelpClient) Recv() (*UserHelpResponse, error) {
	m := new(UserHelpResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility
type UsersServer interface {
	// unary pattern
	GetUser(context.Context, *UserGetRequest) (*User, error)
	// server-side stream
	CreateUser(*User, Users_CreateUserServer) error
	// client-side stream
	GetUsers(Users_GetUsersServer) error
	// bi-directional stream
	GetHelp(Users_GetHelpServer) error
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (UnimplementedUsersServer) GetUser(context.Context, *UserGetRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUsersServer) CreateUser(*User, Users_CreateUserServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUsersServer) GetUsers(Users_GetUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUsersServer) GetHelp(Users_GetHelpServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHelp not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUser(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UsersServer).CreateUser(m, &usersCreateUserServer{stream})
}

type Users_CreateUserServer interface {
	Send(*UserCreateLog) error
	grpc.ServerStream
}

type usersCreateUserServer struct {
	grpc.ServerStream
}

func (x *usersCreateUserServer) Send(m *UserCreateLog) error {
	return x.ServerStream.SendMsg(m)
}

func _Users_GetUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UsersServer).GetUsers(&usersGetUsersServer{stream})
}

type Users_GetUsersServer interface {
	SendAndClose(*UsersList) error
	Recv() (*User, error)
	grpc.ServerStream
}

type usersGetUsersServer struct {
	grpc.ServerStream
}

func (x *usersGetUsersServer) SendAndClose(m *UsersList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *usersGetUsersServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Users_GetHelp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UsersServer).GetHelp(&usersGetHelpServer{stream})
}

type Users_GetHelpServer interface {
	Send(*UserHelpResponse) error
	Recv() (*UserHelpRequest, error)
	grpc.ServerStream
}

type usersGetHelpServer struct {
	grpc.ServerStream
}

func (x *usersGetHelpServer) Send(m *UserHelpResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *usersGetHelpServer) Recv() (*UserHelpRequest, error) {
	m := new(UserHelpRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Users_GetUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateUser",
			Handler:       _Users_CreateUser_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUsers",
			Handler:       _Users_GetUsers_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetHelp",
			Handler:       _Users_GetHelp_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "users.proto",
}
