// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: repos.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Repository) Reset() {
	*x = Repository{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 스트리밍 시작 시에 1번만 전송하는 파일 메타데이터
type RepoContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorName string `protobuf:"bytes,1,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	FileName    string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *RepoContext) Reset() {
	*x = RepoContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoContext) ProtoMessage() {}

func (x *RepoContext) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoContext.ProtoReflect.Descriptor instead.
func (*RepoContext) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{1}
}

func (x *RepoContext) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *RepoContext) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type RepoCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 스트리밍 시작 이후부터는 바이너리 데이터만 스트리밍
	//
	// Types that are assignable to Body:
	//
	//	*RepoCreateRequest_Context
	//	*RepoCreateRequest_Data
	Body isRepoCreateRequest_Body `protobuf_oneof:"body"`
}

func (x *RepoCreateRequest) Reset() {
	*x = RepoCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoCreateRequest) ProtoMessage() {}

func (x *RepoCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoCreateRequest.ProtoReflect.Descriptor instead.
func (*RepoCreateRequest) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{2}
}

func (m *RepoCreateRequest) GetBody() isRepoCreateRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *RepoCreateRequest) GetContext() *RepoContext {
	if x, ok := x.GetBody().(*RepoCreateRequest_Context); ok {
		return x.Context
	}
	return nil
}

func (x *RepoCreateRequest) GetData() []byte {
	if x, ok := x.GetBody().(*RepoCreateRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isRepoCreateRequest_Body interface {
	isRepoCreateRequest_Body()
}

type RepoCreateRequest_Context struct {
	Context *RepoContext `protobuf:"bytes,1,opt,name=context,proto3,oneof"`
}

type RepoCreateRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*RepoCreateRequest_Context) isRepoCreateRequest_Body() {}

func (*RepoCreateRequest_Data) isRepoCreateRequest_Body() {}

type RepoCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo *Repository `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Size int32       `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *RepoCreateResponse) Reset() {
	*x = RepoCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoCreateResponse) ProtoMessage() {}

func (x *RepoCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoCreateResponse.ProtoReflect.Descriptor instead.
func (*RepoCreateResponse) Descriptor() ([]byte, []int) {
	return file_repos_proto_rawDescGZIP(), []int{3}
}

func (x *RepoCreateResponse) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *RepoCreateResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_repos_proto protoreflect.FileDescriptor

var file_repos_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a,
	0x0a, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x4d, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x5b, 0x0a, 0x11, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x49, 0x0a,
	0x12, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x04,
	0x72, 0x65, 0x70, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x32, 0x3d, 0x0a, 0x04, 0x52, 0x65, 0x70, 0x6f,
	0x12, 0x35, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x15, 0x5a, 0x13, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repos_proto_rawDescOnce sync.Once
	file_repos_proto_rawDescData = file_repos_proto_rawDesc
)

func file_repos_proto_rawDescGZIP() []byte {
	file_repos_proto_rawDescOnce.Do(func() {
		file_repos_proto_rawDescData = protoimpl.X.CompressGZIP(file_repos_proto_rawDescData)
	})
	return file_repos_proto_rawDescData
}

var file_repos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_repos_proto_goTypes = []interface{}{
	(*Repository)(nil),         // 0: Repository
	(*RepoContext)(nil),        // 1: RepoContext
	(*RepoCreateRequest)(nil),  // 2: RepoCreateRequest
	(*RepoCreateResponse)(nil), // 3: RepoCreateResponse
}
var file_repos_proto_depIdxs = []int32{
	1, // 0: RepoCreateRequest.context:type_name -> RepoContext
	0, // 1: RepoCreateResponse.repo:type_name -> Repository
	2, // 2: Repo.Create:input_type -> RepoCreateRequest
	3, // 3: Repo.Create:output_type -> RepoCreateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_repos_proto_init() }
func file_repos_proto_init() {
	if File_repos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_repos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Repository); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_repos_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*RepoCreateRequest_Context)(nil),
		(*RepoCreateRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repos_proto_goTypes,
		DependencyIndexes: file_repos_proto_depIdxs,
		MessageInfos:      file_repos_proto_msgTypes,
	}.Build()
	File_repos_proto = out.File
	file_repos_proto_rawDesc = nil
	file_repos_proto_goTypes = nil
	file_repos_proto_depIdxs = nil
}
