// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: repos.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Repo_Create_FullMethodName = "/Repo/Create"
)

// RepoClient is the client API for Repo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepoClient interface {
	Create(ctx context.Context, opts ...grpc.CallOption) (Repo_CreateClient, error)
}

type repoClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoClient(cc grpc.ClientConnInterface) RepoClient {
	return &repoClient{cc}
}

func (c *repoClient) Create(ctx context.Context, opts ...grpc.CallOption) (Repo_CreateClient, error) {
	stream, err := c.cc.NewStream(ctx, &Repo_ServiceDesc.Streams[0], Repo_Create_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &repoCreateClient{stream}
	return x, nil
}

type Repo_CreateClient interface {
	Send(*RepoCreateRequest) error
	CloseAndRecv() (*RepoCreateResponse, error)
	grpc.ClientStream
}

type repoCreateClient struct {
	grpc.ClientStream
}

func (x *repoCreateClient) Send(m *RepoCreateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *repoCreateClient) CloseAndRecv() (*RepoCreateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RepoCreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RepoServer is the server API for Repo service.
// All implementations must embed UnimplementedRepoServer
// for forward compatibility
type RepoServer interface {
	Create(Repo_CreateServer) error
	mustEmbedUnimplementedRepoServer()
}

// UnimplementedRepoServer must be embedded to have forward compatible implementations.
type UnimplementedRepoServer struct {
}

func (UnimplementedRepoServer) Create(Repo_CreateServer) error {
	return status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRepoServer) mustEmbedUnimplementedRepoServer() {}

// UnsafeRepoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoServer will
// result in compilation errors.
type UnsafeRepoServer interface {
	mustEmbedUnimplementedRepoServer()
}

func RegisterRepoServer(s grpc.ServiceRegistrar, srv RepoServer) {
	s.RegisterService(&Repo_ServiceDesc, srv)
}

func _Repo_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepoServer).Create(&repoCreateServer{stream})
}

type Repo_CreateServer interface {
	SendAndClose(*RepoCreateResponse) error
	Recv() (*RepoCreateRequest, error)
	grpc.ServerStream
}

type repoCreateServer struct {
	grpc.ServerStream
}

func (x *repoCreateServer) SendAndClose(m *RepoCreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *repoCreateServer) Recv() (*RepoCreateRequest, error) {
	m := new(RepoCreateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Repo_ServiceDesc is the grpc.ServiceDesc for Repo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Repo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Repo",
	HandlerType: (*RepoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _Repo_Create_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "repos.proto",
}
